# Generated by Django 4.2.16 on 2024-11-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
