# Generated by Django 4.2.16 on 2024-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0004_component_issuedcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='issuedcomponent',
            name='amount',
        ),
        migrations.AddField(
            model_name='issuedcomponent',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
