# Generated by Django 4.2.16 on 2024-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0005_remove_component_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='quantity',
            new_name='quantity_initial',
        ),
        migrations.RemoveField(
            model_name='issuedcomponent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='issuedcomponent',
            name='quantity',
            field=models.PositiveBigIntegerField(default=15),
        ),
    ]
