# Generated by Django 4.2.16 on 2024-11-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0006_rename_quantity_component_quantity_initial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='quantity_initial',
            new_name='quantity',
        ),
    ]
