# Generated by Django 4.2.16 on 2024-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0007_rename_quantity_initial_component_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcomponent',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='issuedcomponent',
            name='returned',
        ),
        migrations.AddField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
