# Generated by Django 4.2.16 on 2024-11-18 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0008_remove_issuedcomponent_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcomponent',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 9, 15, 46, 36874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
