# Generated by Django 4.2.16 on 2024-11-18 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0009_issuedcomponent_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 9, 17, 43, 124719, tzinfo=datetime.timezone.utc)),
        ),
    ]
