# Generated by Django 4.2.16 on 2024-11-18 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0011_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 11, 49, 31, 396803, tzinfo=datetime.timezone.utc)),
        ),
    ]
