# Generated by Django 4.2.16 on 2024-11-18 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0013_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 11, 57, 23, 330686, tzinfo=datetime.timezone.utc)),
        ),
    ]
