# Generated by Django 4.2.16 on 2024-11-18 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0014_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuedcomponent',
            options={'verbose_name': 'Issued Component', 'verbose_name_plural': 'Issued Components'},
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 18, 12, 32, 52, 474724, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
