# Generated by Django 4.2.16 on 2024-11-18 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0015_alter_issuedcomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 17, 31, 29, 993411, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
