# Generated by Django 4.2.16 on 2024-11-19 02:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0016_alter_issuedcomponent_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuedcomponent',
            options={},
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rbtcwebapp.component'),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 2, 19, 57, 646491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
