# Generated by Django 4.2.16 on 2024-11-19 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0017_alter_issuedcomponent_options_component_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('Drone', 'Drone'), ('Battery', 'Battery & Power'), ('Sensors', 'Sensors'), ('Actuators', 'Actuators'), ('IOT', 'IOT'), ('Other', 'Other'), ('Miscellaneous', 'Miscellaneous')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='component',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 2, 43, 27, 314180, tzinfo=datetime.timezone.utc)),
        ),
    ]
