# Generated by Django 4.2.16 on 2024-11-19 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0018_component_category_component_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 7, 18, 22, 729501, tzinfo=datetime.timezone.utc)),
        ),
    ]
