# Generated by Django 4.2.16 on 2024-11-19 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0020_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 7, 42, 57, 21230, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], max_length=10),
        ),
    ]
