# Generated by Django 4.2.16 on 2024-11-19 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0021_alter_issuedcomponent_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='enrollmentnumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='gr_number',
            field=models.CharField(default='DEFAULT_VALUE', max_length=255),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 23, 51, 35, 772290, tzinfo=datetime.timezone.utc)),
        ),
    ]
