# Generated by Django 4.2.16 on 2024-11-19 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0022_rename_user_profile_enrollmentnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='enrollmentnumber',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gr_number',
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 23, 55, 16, 353550, tzinfo=datetime.timezone.utc)),
        ),
    ]
