# Generated by Django 4.2.16 on 2024-11-20 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0023_rename_enrollmentnumber_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 20, 2, 34, 31, 387236, tzinfo=datetime.timezone.utc)),
        ),
    ]
