# Generated by Django 4.2.16 on 2024-11-20 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0024_alter_component_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 20, 2, 42, 48, 947007, tzinfo=datetime.timezone.utc)),
        ),
    ]
