# Generated by Django 4.2.16 on 2024-11-21 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0025_alter_component_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcomponent',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 0, 59, 52, 22447, tzinfo=datetime.timezone.utc)),
        ),
    ]
