# Generated by Django 4.2.16 on 2024-11-21 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0026_issuedcomponent_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 4, 37, 19, 106350, tzinfo=datetime.timezone.utc)),
        ),
    ]
