# Generated by Django 4.2.16 on 2024-11-21 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0028_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 12, 16, 25, 130275, tzinfo=datetime.timezone.utc)),
        ),
    ]
