# Generated by Django 4.2.16 on 2024-11-21 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0031_alter_issuedcomponent_issue_date_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 14, 23, 9, 227802, tzinfo=datetime.timezone.utc)),
        ),
    ]
