# Generated by Django 4.2.16 on 2024-11-22 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0033_category_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcomponent',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
