# Generated by Django 4.2.16 on 2024-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0034_alter_issuedcomponent_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='components/'),
        ),
    ]
