# Generated by Django 4.2.16 on 2024-11-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbtcwebapp', '0035_alter_component_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='image_url',
            new_name='image',
        ),
    ]
